import type { Metadata } from 'next';
import { Outfit } from 'next/font/google';
import './globals.css';
import { Header } from '@/components/layout/header';
import { Footer } from '@/components/layout/footer';

const outfit = Outfit({
  // variable: '--font-outfit',
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  console.log('outfit.className :>> ', outfit.className);
  return (
    <html lang="en" className="w-screen h-screen">
      <body
        className={`${outfit.className} antialiased grid grid-rows-[auto,1fr,auto] min-h-screen w-screen`}
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
