export const stateOptions = [
  { value: 'Caracas', label: 'Caracas' },
  { value: 'Trujillo', label: 'Trujillo' },
  { value: 'Barinas', label: 'Barinas' },
  { value: 'Mérida', label: 'Mérida' },
  { value: 'Portuguesa', label: 'Portuguesa' },
  { value: 'Amazonas', label: 'Amazonas' },
  { value: 'Apure', label: 'Apure' },
  { value: 'Aragua', label: 'Aragua' },
  { value: 'Barinas', label: 'Barinas' },
  { value: 'Bolivar', label: 'Bolivar' },
  { value: 'Carabobo', label: 'Carabobo' },
  { value: 'Cojedes', label: 'Cojedes' },
  { value: 'Delta Amacuro', label: 'Delta Amacuro' },
  { value: 'Distrito Capital', label: 'Distrito Capital' },
  { value: 'Falcon', label: 'Falcon' },
  { value: 'Guarico', label: 'Guarico' },
  { value: 'Lara', label: 'Lara' },
  { value: 'Merida', label: 'Merida' },
  { value: 'Miranda', label: 'Miranda' },
  { value: 'Monagas', label: 'Monagas' },
  { value: 'Nueva Esparta', label: 'Nueva Esparta' },
  { value: 'Portuguesa', label: 'Portuguesa' },
  { value: 'Sucre', label: 'Sucre' },
  { value: 'Tachira', label: 'Tachira' },
  { value: 'Trujillo', label: 'Trujillo' },
  { value: 'Vargas', label: 'Vargas' },
  { value: 'Yaracuy', label: 'Yaracuy' },
  { value: 'Zulia', label: 'Zulia' },
];
