// this file was generated by scripts/update-icons.ts
// please do not edit it manually

export function IconCalendar({ size = 24 }: { size?: number }) {
  return (
    <svg viewBox="0 0 20 20" fill="none" width={size} height={size}>
      <path
        d="M4.16667 18.3334H15.8333C16.7525 18.3334 17.5 17.5859 17.5 16.6667V5.00002C17.5 4.08085 16.7525 3.33335 15.8333 3.33335H14.1667V1.66669H12.5V3.33335H7.5V1.66669H5.83333V3.33335H4.16667C3.2475 3.33335 2.5 4.08085 2.5 5.00002V16.6667C2.5 17.5859 3.2475 18.3334 4.16667 18.3334ZM4.16667 5.83335H15.8333V7.50002H4.16667V5.83335Z"
        fill="currentColor"
      />
    </svg>
  );
}
