// this file was generated by scripts/update-icons.ts
// please do not edit it manually

export function IconArrowBack({ size = 24 }: { size?: number }) {
  return (
    <svg viewBox="0 0 24 24" fill="none" width={size} height={size}>
      <path
        d="M21.0001 11H6.41406L11.7071 5.707L10.2931 4.293L2.58606 12L10.2931 19.707L11.7071 18.293L6.41406 13H21.0001V11Z"
        fill="currentColor"
      />
    </svg>
  );
}
