// this file was generated by scripts/update-icons.ts
// please do not edit it manually

export function IconChevronRight({ size = 24 }: { size?: number }) {
  return (
    <svg viewBox="0 0 8 12" fill="none" width={size} height={size}>
      <path
        d="M1.70694 11.7084L7.41394 6.00143L1.70694 0.294434L0.292938 1.70843L4.58594 6.00143L0.292938 10.2944L1.70694 11.7084Z"
        fill="currentColor"
      />
    </svg>
  );
}
