// this file was generated by scripts/update-icons.ts
// please do not edit it manually

export function IconChevronDown({ size = 24 }: { size?: number }) {
  return (
    <svg viewBox="0 0 14 10" fill="none" width={size} height={size}>
      <path
        d="M12.0085 0.841827L6.99996 5.85033L1.99146 0.841827L0.341797 2.49149L6.99996 9.14966L13.6581 2.49149L12.0085 0.841827Z"
        fill="currentColor"
      />
    </svg>
  );
}
