// this file was generated by scripts/update-icons.ts
// please do not edit it manually

export function IconChevronLeft({ size = 24 }: { size?: number }) {
  return (
    <svg viewBox="0 0 8 12" fill="none" width={size} height={size}>
      <path
        d="M6.293 0.293031L0.586002 6.00003L6.293 11.707L7.707 10.293L3.414 6.00003L7.707 1.70703L6.293 0.293031Z"
        fill="currentColor"
      />
    </svg>
  );
}
