// this file was generated by scripts/update-icons.ts
// please do not edit it manually

export { IconArrowBack } from "./IconArrowBack";
export { IconCalendar } from "./IconCalendar";
export { IconChevronDown } from "./IconChevronDown";
export { IconCopy } from "./IconCopy";
export { IconFilter } from "./IconFilter";
export { IconGift } from "./IconGift";
export { IconInstagram } from "./IconInstagram";
export { IconSearch } from "./IconSearch";
export { IconUser } from "./IconUser";
export { IconWhatsapp } from "./IconWhatsapp";
